//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AquaLangLib.rc
//
#define IDC_BUTTON_CALC_REDUCE          3
#define IDC_BUTTON_CALC_ASSIGN          4
#define IDB_BITMAP_RIGHT_UP_BALLOON     101
#define IDB_BITMAP_LEFT_DOWN_BALLOON    102
#define IDB_BITMAP_LEFT_UP_BALLOON      103
#define IDB_BITMAP_RIGHT_DOWN_BALLOON   104
#define IDB_BITMAP_LITE_RIGHT_UP_BALLOON 105
#define IDB_BITMAP_LITE_LEFT_DOWN_BALLOON 106
#define IDB_BITMAP_LITE_LEFT_UP_BALLOON 107
#define IDB_BITMAP_LITE_RIGHT_DOWN_BALLOON 108
#define IDB_FILE_LANGUAGE_TABLE         109
#define IDD_BALLOONTIPWINDOW_DIALOG     110
#define IDD_DEBUGBALLOONTIPWINDOW_DIALOG 115
#define IDD_DIALOG_WEB_BROWSE           116
#define IDI_ICON_DROP                   118
#define IDC_BUTTON_BACK                 119
#define IDC_BUTTON_FORWARD              120
#define IDC_BUTTON_OPEN_DEFAULT_BROWSER 121
#define IDD_DIALOG_CALCULATOR_TIP       122
#define IDB_BITMAP_CALC_TIP             124
#define IDD_DIALOG_COMPACT_CALCULATOR_TIP 125
#define IDB_BITMAP_WATER_DROP_ICON      130
#define IDD_DIALOG_WEB_BROWSE_PAGE      131
#define IDS_STRING_TYPE                 132
#define IDS_STRING_VALUE                133
#define IDS_STRING_CREATIONTIME         134
#define IDS_STRING_ISMUST               135
#define IDS_STRING_LANGUAGE             136
#define IDS_STRING_WINDOWITEMLIST       137
#define IDS_STRING_PROPERTYLIST         138
#define IDS_STRING_PROPERTY             139
#define IDS_STRING_DATABASEROOTFIELD    140
#define IDS_STRING_RULESROOTFIELD       141
#define IDS_STRING_ITEM                 142
#define IDS_STRING_USERINFO             143
#define IDS_STRING_VERSION              144
#define IDS_STRING_FOCUSEVENTS          145
#define IDS_STRING_LANGUAGECHANGEEVENTS 146
#define IDS_STRING_MANUALLANGUAGECHANGEEVENTS 147
#define IDS_STRING_TEXTLANGUAGECHANGEEVENTS 148
#define IDS_STRING_WEBSEARCHEVENTS      149
#define IDS_STRING_CALCREQUESTEVENTS    150
#define IDS_STRING_WATCHDOGRECOVERYEVENTS 151
#define IDS_STRING_NOTIFICATIONTIMEFIELD 152
#define IDS_STRING_ROOTFIELD            153
#define IDS_STRING_WEBBROWSSTATEFILENAME 154
#define IDS_STRING_APPCONFIG            155
#define IDS_STRING_WEBBROWSERSTATE      156
#define IDS_STRING_OPENASSEARCHER       157
#define IDS_STRING_MANUALLANGUAGEFIXEVENTS 158
#define IDS_STRING_GUESSLANGUAGEADVISEEVENTS 159
#define IDS_STRING_GUESSLANGUAGEACCEPTEVENTS 160
#define IDS_STRING_USERINFOSEQUENCENNUMBER 161
#define IDD_DIALOG_TEXT_ADVISOR_TIP     163
#define IDD_DIALOG_GUESS_LANGUAGE_TIP 164
#define IDB_BITMAP_COMPACT_TIP_DN_RIGHT 165
#define IDB_BITMAP_COMPACT_TIP_UP_RIGHT 166
#define IDB_BITMAP_COMPACT_TIP_DN_LEFT 167
#define IDB_BITMAP_COMPACT_TIP_UP_LEFT 168
#define IDC_STATIC_GUESS_LANGUAGE_PROPORSAL 169
#define IDC_STATIC_TEXT                 1002
#define IDC_BUTTON_COPY_RESULT          1005
#define IDC_EDIT_CALC_RESULT            1006
#define IDC_EDIT_CALC_EXPRESSION        1007
#define IDC_EDIT_COMPACT_CALC_RESULT    1008
#define IDC_BUTTON_CALC_DIG7            1009
#define IDC_BUTTON_CALC_DIG0            1010
#define IDC_BUTTON_CALC_DIG8            1011
#define IDC_BUTTON_CALC_DOT             1012
#define IDC_BUTTON_CALC_DIG9            1013
#define IDC_BUTTON_CALC_BRACKET_OPEN    1014
#define IDC_BUTTON_CALC_DIG4            1015
#define IDC_BUTTON_CALC_DIG5            1016
#define IDC_BUTTON_CALC_DIG6            1017
#define IDC_BUTTON_CALC_DIG1            1018
#define IDC_BUTTON_CALC_DIG2            1019
#define IDC_BUTTON_CALC_DIG3            1020
#define IDC_BUTTON_CALC_PLUS            1021
#define IDC_BUTTON_CALC_BRACKET_CLOSE   1022
#define IDC_BUTTON_CALC_MINUS           1023
#define IDC_BUTTON_CALC_MULTIPLY        1024
#define IDC_BUTTON_CALC_PI              1025
#define IDC_BUTTON_CALC_EXPONENT        1026
#define IDC_BUTTON_CALC_1_DIV_X         1027
#define IDC_BUTTON_CALC_DIVIDE          1028
#define IDC_BUTTON_CALC_CLEAR           1029
#define IDC_BUTTON_CALC_POWER           1030
#define IDC_BUTTON_CALC_COS             1031
#define IDC_BUTTON_CALC_SIN             1032
#define IDC_BUTTON_CALC_TAN             1033
#define IDC_BUTTON_CALC_LAN             1034
#define IDC_BUTTON_CALC_DEG             1036
#define IDC_BUTTON_CALC_RAD             1037
#define IDC_BUTTON_CALC_INV             1038
#define IDC_BUTTON_EQUAL_SIGN           1040
#define IDC_TAB_WEB_BROWSE              1043
#define IDC_STATIC_TEXT_ADVISOR         1045
#define IDC_BUTTON1                     1046
#define IDC_BUTTON_CLOSE_TEXT_ADVISOR   1046

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
